---
# tasks file for vector-role
    - name: Install vector packages
      become: true
      ansible.builtin.yum:
        name: https://packages.timber.io/vector/0.29.1/vector-0.29.1-1.{{ ansible_architecture }}.rpm
        state: present
      notify: Restart vector service
    - name: Configure Vector
      file:
        path: "{{ vector_config_dir }}"
        state: directory
        mode: 0644
      become: true
    - name: Configure Vector | Template config
      ansible.builtin.template:
        src: vector.yml.j2
        mode: 0644
        dest: "{{ vector_config_dir }}/vector.yml"
      become: true
      notify: Restart vector service
    - name: Configure Service
      become: true
      ansible.builtin.template:
        src: vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: 0644